version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  airflow-scheduler:
    image: apache/airflow:2.9.2-python3.9
    container_name: airflow_scheduler
    restart: always
    environment:
      AIRFLOW_DATABASE_CONN: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AIRFLOW_WEBSERVER_HOST: 0.0.0.0
      AIRFLOW_WEBSERVER_PORT: 8080
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW_UID: ${AIRFLOW_UID}
      _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS}

      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./requirements.txt:/opt/airflow/requirements.txt
      - airflow_data:/opt/airflow/data
    depends_on:
      postgres:
        condition: service_healthy
    command: scheduler
    healthcheck:
      test: ["CMD", "airflow", "tasks", "test", "example_dag_id", "example_task_id", "2025-06-10"]
      interval: 30s
      timeout: 30s
      retries: 3


  airflow-webserver:
    image: apache/airflow:2.9.2-python3.9
    container_name: airflow_webserver
    restart: always
    environment:
      AIRFLOW_DATABASE_CONN: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AIRFLOW_WEBSERVER_HOST: 0.0.0.0
      AIRFLOW_WEBSERVER_PORT: 8080
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW_UID: ${AIRFLOW_UID}
      _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./requirements.txt:/opt/airflow/requirements.txt
      - airflow_data:/opt/airflow/data
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5

  # Initializing Airflow DB (optional, có thể chạy bằng tay nếu muốn)
  # airflow-init:
  #   image: apache/airflow:2.9.2-python3.9
  #   container_name: airflow_init
  #   environment:
  #     AIRFLOW_DATABASE_CONN: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
  #     AIRFLOW_HOME: /opt/airflow
  #     _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS}
  #   volumes:
  #     - ./dags:/opt/airflow/dags
  #     - ./scripts:/opt/airflow/scripts
  #     - ./requirements.txt:/opt/airflow/requirements.txt
  #     - airflow_data:/opt/airflow/data
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   command: bash -c "airflow db migrate && airflow users create --username airflow --password airflow --firstname Airflow --lastname User --role Admin --email airflow@example.com"


volumes:
  pgdata:
  airflow_data: