version: '3.8'

# Loại bỏ dòng "env_file:" ở đây

services:
  # --- PostgreSQL Database Service ---
  postgres:
    image: postgres:13
    container_name: airflow_postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - airflow_network

  # --- pgAdmin Service ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: airflow_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - airflow_network

  # --- Airflow Scheduler Service ---
  airflow-scheduler:
    image: apache/airflow:2.9.2-python3.9
    container_name: airflow_scheduler
    restart: always
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW_UID: ${AIRFLOW_UID}
      _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS}
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
    volumes:
      - ./dags:/opt/airflow/dags
      - ./ETLScripts:/opt/airflow/scripts
      - ./requirements.txt:/opt/airflow/requirements.txt
      - airflow_data:/opt/airflow/data
    depends_on:
      postgres:
        condition: service_healthy
    command: scheduler
    healthcheck:
      test: ["CMD", "airflow", "db", "check"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - airflow_network

  # --- Airflow Webserver Service ---
  airflow-webserver:
    image: apache/airflow:2.9.2-python3.9
    container_name: airflow_webserver
    restart: always
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AIRFLOW_WEBSERVER_HOST: 0.0.0.0
      AIRFLOW_WEBSERVER_PORT: 8080
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW_UID: ${AIRFLOW_UID}
      FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${FERNET_KEY}
      _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS}
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD}
      _AIRFLOW_WWW_USER_FIRSTNAME: ${_AIRFLOW_WWW_USER_FIRSTNAME}
      _AIRFLOW_WWW_USER_LASTNAME: ${_AIRFLOW_WWW_USER_LASTNAME}
      _AIRFLOW_WWW_USER_EMAIL: ${_AIRFLOW_WWW_USER_EMAIL}
      _AIRFLOW_WWW_USER_ROLE: ${_AIRFLOW_WWW_USER_ROLE}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./ETLScripts:/opt/airflow/scripts
      - ./requirements.txt:/opt/airflow/requirements.txt
      - airflow_data:/opt/airflow/data
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - airflow_network

# --- Docker Volumes ---
volumes:
  pgdata:
  airflow_data:

# --- Docker Networks ---
networks:
  airflow_network:
    driver: bridge